### ISSUE TITLE
option for viewport height

### ISSUE THREAD

**Issue by abenrob** [ajam/banquo#4]
Any reason there is no option for setting the viewport height? easy pull if you aren't opposed to it.

**Comment by mhkeller** [comment]
Yea i think I left it out of the config options because it didn't seem to have an effect. If you give it a selector it accurately sizes according to those dimensions and I didn't have a use cause to debug further. By all means give it a crack. 

I put the example in a file called 'test.js' as just a basic thing. I suppose a better way would be to set up a page on gh-pages or a local server you would hit and compare the base64 strings.

**Comment by abenrob** [comment]
Hm. I'll try it out with a n element that is bigger than the viewport. I'm using to create images for a charting app, and one of the 'chart' types is table; the table can be very tall, so it scrolls out of the standard viewport. I'll try and test to see if selector overrides viewport in this case.

**Comment by mhkeller** [comment]
Interesting. That sounds different from the behavior I had where it would give you the entire HTML view in one long image. The problem was that giving it a smaller height would have no effect. I can't remember if I was using a selector, tho. I'll be at a computer later and can look back. I think it might be the example in one of the early versions of the readme, which will be in the git history.

**Comment by abenrob** [comment]
selector overrides viewport. Awesome! No need for this for me in this case - closing.

**Comment by abenrob** [comment]
Well actually the default viewport height was tall enough for my test case... I have no data in the app long enough to test against, so I'll leave closed until/unless I come across it.
Cheers!
